pipeline:
  test:
    group: test
    image: ${IMAGE}
    environment:
      - CARGO_TERM_COLOR=always
      - CARGO_BUILD_TARGET=${TARGET}
    commands:
      - ${PACKAGE_MANAGER} update
      - ${PACKAGE_MANAGER} ${INSTALL_CMD} -q ${PACKAGE}
      - rustup default stable
      - rustup target add ${TARGET}
      - rustup component add clippy
      - cargo test
      - cargo clippy

  build:
    group: build
    image: ${IMAGE}
    when:
      event: tag
    environment:
      - CARGO_TERM_COLOR=always
      - CARGO_BUILD_TARGET=${TARGET}
    commands:
      - ${PACKAGE_MANAGER} update
      - ${PACKAGE_MANAGER} ${INSTALL_CMD} -q ${PACKAGE}
      - rustup default stable
      - rustup target add ${TARGET}
      - cargo build --profile optimized
      - tar -zcvf file-rs-${TARGET}.tar.gz target/${TARGET}/optimized/file-rs

  publish:
    group: publish
    image: woodpeckerci/plugin-gitea-release
    when:
      event: tag
    settings:
      base_url: https://codeberg.org
      files:
        - "file-rs-${TARGET}.tar.gz"
      file-exists: overwrite
      api_key:
        from_secret: CODEBERG_ACCESS_TOKEN
      target: main
      title: file-rs
      skip_verify: true

matrix:
  include:
    ## musl
    - IMAGE: rust:alpine
      TARGET: x86_64-unknown-linux-musl
      PACKAGE_MANAGER: apk
      INSTALL_CMD: add
      PACKAGE: musl-dev
    - IMAGE: rust:alpine
      TARGET: aarch64-unknown-linux-musl
      PACKAGE_MANAGER: apk
      INSTALL_CMD: add
      PACKAGE: "gcc-aarch64-none-elf musl-dev"
      CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER: aarch64-none-elf-gcc
    ## gnu/glibc
    - IMAGE: rust:latest
      TARGET: x86_64-unknown-linux-gnu
      PACKAGE_MANAGER: apt
      INSTALL_CMD: install
      PACKAGE: gcc
    - IMAGE: rust:latest
      TARGET: aarch64-unknown-linux-gnu
      PACKAGE_MANAGER: apt
      INSTALL_CMD: install
      PACKAGE: gcc-aarch64-linux-gnu
      CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
    # - TARGET: x86_64-pc-windows-gnu
    #   IMAGE: rust:latest
    #   PACKAGE: windows/amd64
    # - TARGET: x86_64-pc-windows-msvc
    #   IMAGE: rust:latest
    #   PACKAGE: windows/amd64
